### ISSUE TITLE
Distance and Travel Time do not appear in the Responders Console

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#103]
The Distance and Travel Time do not appear next to each available responder in the Dispatch Console suggesting that the Google API key is broken.

**Comment by jasonwinget** [comment]
@OhMcGoo if you remove the two county names from the old territory it should stop matching on the "first" it finds in the database.  The enabled/disabled doesn't seem to matter to the matching.  However, if you remove the match all together from the list it should find the "newer" record in the database.

**Comment by bnazari** [comment]
New API keys was added. Please monitor and advise!

**Comment by cecilia-donnelly** [comment]
Hey @bnazari, you mentioned replacing the `durationInTraffic` field with `drivingOptions` -- have you been able to test that?

**Comment by cecilia-donnelly** [comment]
See @bnazari's comment [on the list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dcsops-dev/vUACR0BU868).

**Comment by kfogel** [comment]
So, to summarize:

This is apparently not just a matter of updating the API key (which @bnazari [already did](https://github.com/redcross/arcdata/issues/103#issuecomment-348045067)).  We also have to change the `durationInTraffic` field to `drivingOptions`, because of this change to the API (quoting from [@bnazari's post](https://groups.google.com/d/msg/dcsops-dev/vUACR0BU868/P9NyqpzQAwAJ), which in turn quotes from [Google's documentation](https://developers.google.com/maps/documentation/javascript/distancematrix)):

> Note: The durationInTraffic field is now deprecated. It was previously the recommended way for Google Maps APIs Premium Plan customers to specify whether the result should include a duration that takes into account current traffic conditions. You should now use the drivingOptions field instead.

@bnazari, it sounded like you have a PR in progress for this?  Ready to share?

**Comment by kfogel** [comment]
@bnazari said he doesn't have a PR for this, so it's fresh.  Anyone can pick it up.
