### ISSUE TITLE
Dispatch requests collected by DirectLine are not creating incident reports in DCSOps

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#161]
Here is the initial notification from the Cascades Region:

Hello,
 
I am the on-call manager for the Cascades Region in Oregon and Southwest Washington.  Since early this morning our incidents are not populating in DCSOps.  We are receiving notification from our dispatch service, but the events are not coming as an email from DCSOps and there is not an incident for us document our activities.
 
Please follow-up confirmation you received this inquiry and please provide status updates as you are working to resolve it.
 
Thank you,
Curtis
 
Curtis Peetz │Regional Planning and Readiness Manager
American Red Cross Cascades Region
(503) 528-5669 (p) │(971) 563-6664 (c)
curtis.peetz@redcross.org

**Comment by OhMcGoo** [comment]
Here is my initial reply to Curtis:

Curtis:

I have no relationship with your dispatch service, DirectLine, and have little knowledge of how their call center software interfaces with DCSOps. However, we will take a look to see if DCSOps is preventing the transfer of incident data. In the meantime, you will have to create incidents manually.

Is anyone else in the Pacific Division experiencing this issue?


Jim McGowan
American Red Cross
312-848-6726 (m)
jim.mcgowan@redcross.org

**Comment by pjsier** [comment]
I'm seeing new incidents imported from Postmark in the logs, so I think we can consider this closed. For future reference, noting here these imports are processed by an inbound mail hook that wasn't running because the credit card information was no longer valid. Postmark apparently doesn't send a warning email when payment information doesn't work, it just stops processing emails (which seems odd)
