### ISSUE TITLE
Change entity names

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#185]
Change entity names system-wide:

- Change Chapters to **Regions**
- Change Counties to **Territories**
- Change Territories to **Counties**
- Change Roles to **Capabilities**

It is understood that this is not simply a matter of cutting and pasting and that relationships between user-seen designations and database nomenclature will have to be explored.

Note that while it may be tempting to also change "Positions" to "Roles" (once the old "Roles" has been moved to "Capabilities" as per above), but we don't want to rename "Positions", because that's a term of art within American Red Cross dispatching and we don't want to gratuitously diverge from it.

**Comment by kfogel** [comment]
Note that @frankduncan and I have taken to calling this issue "The Full #185", because doing it right means redoing the DB schema and some underlying relationships in order to make the system much easier to maintain thereafter.  That's why Jim gave it the "XL" label.

Specifically, we need to reflect the Red Cross organizational structure...

`Zip -> City -> County -> Chapter -> Region -> Divisions`

...and then implement the idea of a `Response Territory`, which cuts across `Zip -> ... -> Chapter` above.  A RT represents some person's/group's/process's area of responsibility.  A RT _can_ cross chapters, but often a RT will just be coterminous with a Chapter.

Right now, counties in DCSOps don't map to actual counties.  They're arbitrary creations whose relationships with actual counties are tenuous at best.  They map how a request gets to a person.

**Comment by frankduncan** [comment]
More clarity as part of this:

* Counties renamed to ShiftTerritories
* Territories renamed to ResponseTerritories
* Counties to be created that represent physical counties

Also, another rename came up as useful

* Rename ShiftGroups to ShiftTimes

**Comment by frankduncan** [comment]
As of right now, a ResponseTerritory (in new nomenclature) is assigned to an incident based on city, zip, or county.  There was a thought that this assignment could be done in real time, but that would require a more substantial effort due to building a query that matches against all the correct combinations of places an incident can belong in, or in building out extra tables to represent these different concepts.

So usual cache invalidate rules apply.

**Comment by OhMcGoo** [comment]
Any difference if we do Shift_Territories, Response_Territories and Shift_Times?

**Comment by frankduncan** [comment]
@OhMcGoo That's just rails naming convention for the classes.  ShiftTerritory will get turned into shift_territories in the database, and then we can control the UI to add spaces or underscores to urls and pages as appropriate

**Comment by OhMcGoo** [comment]
Coolio.

**Comment by frankduncan** [comment]
Work is currently going on on 185-rename-tables branch

**Comment by kfogel** [comment]
I'm so sorry you didn't call the branch `185-the-big-185`. :-)

**Comment by OhMcGoo** [comment]
This is BIG!

**Comment by OhMcGoo** [comment]
After reviewing the staging site, I have only a few minor comments:

On the DAT Scheduling page, the **Shift Territory Shifts** button should be renamed and the **Select Highlighting** and **Show Shifts For** columns should be swapped:
<img width="1276" alt="DAT Scheduling" src="https://user-images.githubusercontent.com/4147733/87228484-2cddc280-c367-11ea-83b1-75bacd6d6bd5.png">

On any page where a map is shown, Google Maps can't load an image:
<img width="1276" alt="Google Maps can't load" src="https://user-images.githubusercontent.com/4147733/87228492-36ffc100-c367-11ea-9a40-93fa18b69b29.png">

This is small and probably not an issue but when creating an incident, some of the fields in staging have shifted left . . .
<img width="1276" alt="Create Incident (Flush left)" src="https://user-images.githubusercontent.com/4147733/87228517-60205180-c367-11ea-8f15-cf570a5e1add.png">

. . . versus where they appear in production:
<img width="1276" alt="Create Incident (Indent)" src="https://user-images.githubusercontent.com/4147733/87228525-66aec900-c367-11ea-92e5-5e108bca0120.png">

Finally, this question is not necessarily related to this issue, however, I'll ask: What is the purpose of a Regional Admin?
<img width="1276" alt="Region Admin?" src="https://user-images.githubusercontent.com/4147733/87228530-6f9f9a80-c367-11ea-81d0-32ceba393173.png">

**Comment by frankduncan** [comment]
All has been resolved and pushed into staging.

As for Region Admins, that appears to be a way to administrate various fields of the Region objects which are only available to people with a certain administration level.  Of note, you can go into editing cni, and then change the URL to "gny" and be able to edit that one, so the security isn't really that great.

**Comment by OhMcGoo** [comment]
@frankduncan: Should Region Admin be renamed **Site Admin**?

**Comment by frankduncan** [comment]
> @frankduncan: Should Region Admin be renamed **Site Admin**?

@OhMcGoo I have no idea!  I'm not super sure what the fields in here are for, though they seem to have something to do with Volunteer Connection.  I think we may want to hold off renaming until we actually just figure out what the different permissions different people should have around administrating the site, a la #166
