### ISSUE TITLE
Remove Spreadsheet links from DAT Scheduling page

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#187]
On the **DAT Scheduling** page, under **Calendar Details**, remove the Spreadsheet links listed under the current and next two months.

![DAT Scheduling](https://user-images.githubusercontent.com/4147733/63186052-1331df00-c021-11e9-958f-d80400675688.png)

**Comment by kfogel** [comment]
Note that this is because the functionality (on the page after you click the link) is essentially broken -- you can't actually download a spreadsheet.  So when we fix this issue, we should make sure another one is filed reminding us that some day we'd like to actually get spreadsheets working.  However, until they are, let's just remove the links so they don't distract or mislead people.

**Comment by frankduncan** [comment]
How's it supposed to work?  Might be a quick fix to just have the spreadsheets work.

**Comment by frankduncan** [comment]
@OhMcGoo ^^

**Comment by frankduncan** [comment]
It looks like it's blank because the "spreadsheet_ordinal" for shifts isn't being sent in the admin console.  THe "ordinal" is being set, but there needs to be a "spreadsheet_ordinal" too.  When I set that on the "Greater Chicago - Greater Chicago" shift to 2001, the spreadsheet starts working.

**Comment by OhMcGoo** [comment]
@frankduncan: I think it produced an actual spreadsheet that looked something like this:
[grid.pdf](https://github.com/redcross/arcdata/files/4873882/grid.pdf)

The functionality, conceptually, is good but the execution is bad (and ugly). It might be worth keeping but we'd need to design it better. Maybe, instead of **Spreadsheet**, it could say **Print Schedule**. Then we fix up the linked page and the output.

Still, it seems like a lotta work.

**Comment by frankduncan** [comment]
Change "Spreadhsheet" to "Printable" and remove Grid is the new definition of this issue.
