### ISSUE TITLE
Create a Response Status field separate from Incident Types

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#205]
Incident Types:

<img width="308" alt="incident type" src="https://user-images.githubusercontent.com/4147733/65618767-7863e300-df84-11e9-9f2a-7b013b4f6b16.png">

Response Status:

- Open
- Closed
- Duplicate
- Invalid
- No response needed
- Not eligible for services

**Comment by kfogel** [comment]
Programmer-speak overview here:

There are various pages where, if you close an incident as "No response needed" or "Invalid", the **incident type** gets displayed as that from then on -- instead of as, you know, an actual incident type, like "Fire" or "Flood" or whatever.

That's a bizarre category mixing.  We don't know how deep this problem goes.  Heck, I don't even quite understand how it's *possible* to get those inappropriate values into those fields.  I mean, aren't these essentially enum types under the hood somewhere?  Please?

Anyway, we'll figure it out.  This note is just to confirm to whoever looks at this next that, yes, the problem really is as weird as it sounds.  Ask @OhMcGoo to demonstrate it.

**Comment by frankduncan** [comment]
The way the code works in general is that the status should be either Open, Closed, or Invalid.  In the case of the latter, I'll add a new DB column "reason_marked_invalid" and then when displaying the status on the incident page, it will say something like "Invalid - Duplicate" or "Invalid - No response needed"

**Comment by frankduncan** [comment]
One last question is where to put this information?
![incident_status](https://user-images.githubusercontent.com/5125316/87223595-f6db1700-c343-11ea-8a14-186ac96d96e0.png)
  Right now, because it's the status of the issue, I'm putting it on top, in the same font as the incident number.  See screenshot

**Comment by OhMcGoo** [comment]
@frankduncan: So, let me simply confirm . . . We now have five possible statuses:

- Open
- Closed
- Invalid - Duplicate
- Invalid - No Response Needed
- Invalid - Not Eligible for Services

**Comment by frankduncan** [comment]
There's also "Invalid - <no reason given>" which displays as "Invalid" and "Invalid - Invalid" which displays as "Invalid"

**Comment by OhMcGoo** [comment]
@frankduncan: OK, let me give this some thought. I want to finish reviewing the staging site and then I'll return my attention to this issue.

**Comment by OhMcGoo** [comment]
@frankduncan: How about something like this where "Response" is also added as a Status qualifier:

<img width="1276" alt="Status" src="https://user-images.githubusercontent.com/4147733/87228890-d8881200-c369-11ea-8856-a0709122da9d.png">

**Comment by frankduncan** [comment]
Response is not a currently tracked status, so when does it get that status? And that might be a bigger change than what we've been talking about because it gets into the workflow.

But as for putting the status under the Response table, that's easy enough.

**Comment by OhMcGoo** [comment]
@frankduncan: Any incident that's NOT Invalid counts as a **Response**.

**Comment by frankduncan** [comment]
So we want "Response - Open" and "Response - Closed" vs "Invalid - Duplicate"?
