### ISSUE TITLE
NCCR Initial Incident Reports (IIRs) being sent multiple times after initial approval

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#232]
**Initial Incident Reports** (IIRs) created by the Northern California Coastal Region (NCCR) are being created, saved in the Attachments tab (of the respective DCSOps incident report) and sent multiple times to a preset distribution list (see Admin > Roster > Chapters > Northern California Coastal Region > Iir e-mails). A recent test earlier today saw nine IIRs created and distributed (after a single approval) at the following times (all PDT):

1. 4/9 3:41pm
2. 4/9 3:41pm
3. 4/9 3:42pm
4. 4/9 3:43pm
5. 4/9 3:48pm
6. 4/9 3:58pm
7. 4/9 4:20pm
8. 4/9 5:00pm
9. 4/9 6:09pm

![NCCR IIRs](https://user-images.githubusercontent.com/4147733/78953983-4ccbc480-7aa0-11ea-8209-243ad0818fbe.png)

Note that indent type was **Exercise** when the IIR was initially approved. It was then changed to **Fire** afterwards. Seven of the IIRs were sent with **Fire** as the incident type.

![IIR tab](https://user-images.githubusercontent.com/4147733/78954260-235f6880-7aa1-11ea-9804-2d36a6231ec0.png)

**Comment by OhMcGoo** [comment]
Note: I tested creating and approving an IIR in the Chicago & Northern Illinois Region. Only one IIR was created and distributed:

![CNIL IIR](https://user-images.githubusercontent.com/4147733/78955143-efd20d80-7aa3-11ea-93b6-4699b75fd845.png)

**Comment by kfogel** [comment]
Thanks for the report!

First, I'd like to understand the problem a bit more thoroughly.  Let me restate it, and you tell me if I've got it right:

Some person in NCCR (btw, NCCR's abbrevation in DCSOps is `gsr`, in case anyone's hacking URLs to get to the right chapter) created an incident: 20-1348.  So far so good -- no problems yet.  Then someone (a responder in the field?) did an "initial incident report" (IIR) for that existing incident.   Now, that IIR *should* go out to a preset distribution list (the `IIR EMAILS` field on https://www.dcsops.org/scheduler_admin/chapters/gsr) -- that is expected.  But it should only go out once, i.e., be sent once to each email address in that list.  Instead, what's happening is that it's being sent to the distribution list multiple times -- perhaps infinity times, and we just haven't let the loop run long enough yet.  Also, once an IIR is made, it becomes available as an attachment (again, that much is expected, right?) and the attaching-to-incident part is also happening in a loop.

Have I got this basically right?

Now, when logged in to DCSOps as Jim, I can reach https://www.dcsops.org/incidents/gsr/incidents to view recent NCCR (`gsr`) incidents.  But when I click on any incident number to view it, including the only Open incident on the page, namely the one we care about (https://www.dcsops.org/incidents/gsr/incidents/20-1348), I get brought back to the same incident list page (https://www.dcsops.org/incidents/gsr/incidents), which now has a pink message box at the top: "You are not authorized to access that page." (presumably referring to the specific incident page that I tried to visit).

@OhMcGoo , does it behave the same way for you?  Is there any way I can view the incident's page?  And can you please share all the relevant URLs that you're looking at while you're logged in?  (Especially given that I don't have the navigational familiarity with the app that you have, having URLs here will save a lot of time.)

A few observations:

1.  The "Exercise" -> "Fire" change *seems* likely not relevant, since the first duplicate IIR went out before that change, as far as we can tell.  I'm not saying we should completely forget about the change in the incident type being a possible trigger, but it's not the first explanation I'd jump at.

2. A much more relevant fact is this: the *only* other chapter that has a non-empty "IIR_EMAILS" field is Gold Country (https://www.dcsops.org/scheduler_admin/chapters/gold_country).  (Incidentally, note that the two chapters have one point of overlap in their "IIR_EMAILS" lists: `denise.everhart {_AT_} redcross.org` appears in both.)

So Jim, if you do a test incident and IIR with Gold Country, do we see the same bug?  If we do, then merely having a non-empty "IIR_EMAILS" field is suddenly likely enough to trigger this.

One last question for now: Does the bug here sound similar to or reminiscent of any other problem(s) you remember DCSOps ever having?  I don't mean that to be a leading question -- if this doesn't remind you (@OhMcGoo or @bnazari) of anything from the past, then "no" is a perfectly fine answer.  I'm just trying to grab any shortcuts that might be available.

**Comment by kfogel** [comment]
Note that the Papertrail log archives covering the relevant time period (2020-04-09 11:41pm UTC - - 2020-04-10 2:09am UTC) won't be available until tomorrow.  We can still search in the Papertrail live-scroll viewer for recent stuff, though.

**Comment by kfogel** [comment]
FYI I've started collecting logs in the usual bigdata repository: https://svn.opentechstrategies.com/repos/bigdata/trunk/clients/red-cross/dcsops/maintenance/logs/2020-04-09-iir-proliferation-issue-232/

**Comment by OhMcGoo** [comment]
See my replies inline.


On Apr 9, 2020, at 9:17 PM, Karl Fogel <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the report!

First, I'd like to understand the problem a bit more thoroughly. Let me restate it, and you tell me if I've got it right:

Some person in NCCR (btw, NCCR's abbrevation in DCSOps is gsr, in case anyone's hacking URLs to get to the right chapter) created an incident: 20-1348. So far so good -- no problems yet. Then someone (a responder in the field?) did an "initial incident report" (IIR) for that existing incident. Now, that IIR should go out to a preset distribution list (the IIR EMAILS field on https://www.dcsops.org/scheduler_admin/chapters/gsr) -- that is expected. But it should only go out once, i.e., be sent once to each email address in that list. Instead, what's happening is that it's being sent to the distribution list multiple times -- perhaps infinity times, and we just haven't let the loop run long enough yet. Also, once an IIR is made, it becomes available as an attachment (again, that much is expected, right?) and the attaching-to-incident part is also happening in a loop.

Those who can create IIRs are usually a very small number and typically staff.


Have I got this basically right?

Basically!


Now, when logged in to DCSOps as Jim, I can reach https://www.dcsops.org/incidents/gsr/incidents to view recent NCCR (gsr) incidents. But when I click on any incident number to view it, including the only Open incident on the page, namely the one we care about (https://www.dcsops.org/incidents/gsr/incidents/20-1348), I get brought back to the same incident list page (https://www.dcsops.org/incidents/gsr/incidents), which now has a pink message box at the top: "You are not authorized to access that page." (presumably referring to the specific incident page that I tried to visit).

Yes, I have to impersonate someone with IIR privileges in the respective region.


@OhMcGoo<https://github.com/OhMcGoo> , does it behave the same way for you? Is there any way I can view the incident's page? And can you please share all the relevant URLs that you're looking at while you're logged in? (Especially given that I don't have the navigational familiarity with the app that you have, having URLs here will save a lot of time.)

Incident report details: https://www.dcsops.org/incidents/gsr/incidents/20-1348

Incident report IIR tab: https://www.dcsops.org/incidents/gsr/incidents/20-1348#inc-iir

Incident report attachements: https://www.dcsops.org/incidents/gsr/incidents/20-1348#inc-attachments


A few observations:

  1.  The "Exercise" -> "Fire" change seems likely not relevant, since the first duplicate IIR went out before that change, as far as we can tell. I'm not saying we should completely forget about the change in the incident type being a possible trigger, but it's not the first explanation I'd jump at.

It may be somewhat relevant because you can’t, technically, approve an IIR unless a certain number of required fields are completed. I deleted the information from many of theses fields and yet, incomplete IIRs are still sent.

  1.
  2.  A much more relevant fact is this: the only other chapter that has a non-empty "IIR_EMAILS" field is Gold Country (https://www.dcsops.org/scheduler_admin/chapters/gold_country). (Incidentally, note that the two chapters have one point of overlap in their "IIR_EMAILS" lists: denise.everhart {_AT_} redcross.org<http://redcross.org> appears in both.)

Actually the two regions have several overlapping recipients. And many regions send IIRs to docc@redcross.org<mailto:docc@redcross.org>.


  1.

So Jim, if you do a test incident and IIR with Gold Country, do we see the same bug? If we do, then merely having a non-empty "IIR_EMAILS" field is suddenly likely enough to trigger this.

I have not tried it but can tomorrow morning.


One last question for now: Does the bug here sound similar to or reminiscent of any other problem(s) you remember DCSOps ever having? I don't mean that to be a leading question -- if this doesn't remind you (@OhMcGoo<https://github.com/OhMcGoo> or @bnazari<https://github.com/bnazari>) of anything from the past, then "no" is a perfectly fine answer. I'm just trying to grab any shortcuts that might be available.

No, this is new one!

**Comment by kfogel** [comment]
Regarding this:

> Actually the two regions have several overlapping recipients. And many regions send IIRs to docc {_AT_} redcross.org

Hunh, I'm confused.  I looked at every chapter listed on https://www.dcsops.org/scheduler_admin/chapters (I realize I'm using "chapter" now but you're saying "region", and this is part of the confusion caused by issue #185) and exactly two of them had *anything* listed in the "IIR_EMAILS" field.  Those two are Gold Country (`gold_country`) and NCCR (`gsr`).  For those two, the only overlap between the two lists is Denise Everhart.  (The `docc@` address only appears in NCCR's list, not in Gold Country's list.)

Now, it may well be that many regions send IIRs to docc@, and it may well be that there are several overlapping recipients between those two regions (argh, "chapters"?) specifically.  **BUT**, if so, that is not being reflected in the actual "IIR_EMAILS" field on the chapter's administrative page -- so those recipient addresses you're talking about must be coming from somewhere else, and I'd like to know where.

Can you be more specific about what you meant by "the two regions have several overlapping recipients" ?

(I don't know that any of this gets us closer to resolving the bug, but if there's a disagreement about facts we need to get to the bottom of it right away -- often such disagreements turn out to reveal different sources of information, which can be very useful.)

When you write this:

> ...I have to impersonate someone with IIR privileges in the respective region.

Are you able to do that?  If so, can you empower me to do it too?  Right now I can't even look at the pages that would, presumably, show the duplicate IIR attachments.

**Comment by OhMcGoo** [comment]
I overstated (and I had temporarily removed our IIR distro list to do some clean-up . . . It's back now). And there are actually two ways to send an IIR (which I will explain later when we meet), thus, the confusion.

And yes, I can empower you to impersonate . . .

**Comment by kfogel** [comment]
I've formed an initial hypothesis, for which we have no particular evidence yet:

If one or more of the email addresses in the IIR_EMAILS list is bouncing with some kind of delivery error that DCSOps's email-sending code can detect, then perhaps DCSOps tries to resend, and maybe the way it does so is to re-run the entire IIR registration process.

**Comment by OhMcGoo** [comment]
All NCCR (gsr) e-mail addresses in the IIR-EMAILS list are working properly (when I e-mail each directly) though DCSOps-generated messages may still be bouncing.

**Comment by jlaxson** [comment]
This looks relevant:

**Comment by kfogel** [comment]
Hey, @jlaxson, thanks.  @OhMcGoo, here's a test we could do -- somewhat laborious, but it would get at the distinction @jlaxson seems to be remarking on:

For each email address in the NCCR "IIR_EMAILS" list, put that address into the Gold Coast "IIR_EMAILS" list -- one address at a time -- and do a test IIR.  If the problem recurs, this time with Gold Coast, then the distinction between you sending an email manually and DCSOps sending it out matters.  (I'm not sure whether it's worth also trying this technique with whatever internal incident notification groups may be set up; let's try with "IIR_EMAILS" first I guess.)

It is quite possible for DCSOps to see different email-sending/receiving behavior than you personally would see, by the way.  For example, a recipient domain's spam filters might treat email coming from DCSOps differently.

In the meantime, I will look in the logs (which we should have now, as per [above](https://github.com/redcross/arcdata/issues/232#issuecomment-611845079)) to search for bounce or non-delivery messages.

@jlaxson, any ideas welcome (re what to look for in the logs, areas of the code that you suspect might be related to this, etc).

**Comment by kfogel** [comment]
@OhMcGoo Other useful tests to perform:

1. Does creating a new incident in NCCR and filing an IIR for it result in the same behavior?  I.e., is this reproducible?
2. You could try *removing* addresses one at a time -- from among the set of addresses you recently added, as discussed today when we talked -- from the NCCR "IIR_EMAILS" list, and then repeat step (1) above.  If removing a particular address suddenly causes the bug to not reproduce, then we're on to something.

**Comment by jlaxson** [comment]
I’d assume it’s just extra whitespace or something in the field, or if not that maybe there’s an address in “First Last <email@domain.com <mailto:email@domain.com>>” format rather than just “email@domain.com <mailto:email@domain.com>”.  Or more unlikely, an email added has whatever the separator character is and it’s getting split into two invalid components?

**Comment by kfogel** [comment]
Thanks, @jlaxson.  I didn't notice anything like that when I was looking at the "IIR_EMAILS" field for NCCR as it's displayed through the web interface -- but it could well be that there's something amiss in the actual data.

It is supposed to be a comma separated list of email addresses, right?

(By the way, if you want to see the actual data, I can send it to you.  Obviously I'd rather not paste email address data into a public issue, but if your Red Cross email address is still valid, I can send it there.  Or if you can log in, it's visible in both the "CONFIG" field and down at the bottom in the "IIR_EMAILS" field of https://www.dcsops.org/scheduler_admin/chapters/gsr .)

@OhMcGoo, aside from "IIR_EMAILS", are there any other notification groups for NCCR that receive notifications for an IIR?

**Comment by kfogel** [comment]
Problem solved, in a rather triumphant joint debugging meeting with @bnazari and @OhMcGoo just now:

The last three email addresses in the IIR_EMAILS list had a "​" (a [Zero-Width Space](https://en.wikipedia.org/wiki/Zero-width_space), Unicode 8203) right after the end of the address (i.e., between the end of the address and the following comma, for two of the addresses, and the last address of course does not have a comma after it but still had a Zero-Width Space).  This caused email delivery of the IIR to fail and report "syntax errors" in the email addresses.  Then it would fall back and retry.

So two incidents (the original 20-1348 and, we discovered today, 20-1341 as well) were apparently constantly retrying to send their IIRs.  The retry loop does exponential backoff: the retries get farther and farther apart, but do keep happening, up to 25 times.

We removed the zero-width space characters from the value in the "IIR_EMAILS" field, and @bnazari also set the IIR retry count for those two incidents to 25 so they'd stop trying, since everyone knows about the incidents anyway and doesn't need to see more noise.  @OhMcGoo will go in and manually do whatever needs to be done with those IIRs now.

This should be resolved now.  Closing this ticket.  Thanks, @bnazari and @OhMcGoo!

**Comment by kfogel** [comment]
Oh, @jlaxson, nick-flagging you because I thought you might want to know that this had been resolved and what the resolution was.  You were absolutely on the right track: it was spurious characters in the field value -- unfortunately, not only spurious, but also invisible to the unaided eye.

**Comment by jlaxson** [comment]
Yay unicode!  Glad you got it sorted out, and appreciate all of you guys continuing to take care of this.

**Comment by OhMcGoo** [comment]
John Ruiz, RDO of NCCR, just sent the following:

**Re: Initial Incident Report for 20-1348 Fire in Northern California Coastal Region**

On Apr 18, 2020, at 11:14 AM, Ruiz, John <john.ruiz2@redcross.org> wrote:

﻿ Huh, just got a stay IIR. Another extra character? Sorry to be such a pest. 
J

**Comment by OhMcGoo** [comment]
I think he meant ‘stray’ IIR.

Did we fully the job?

**Comment by kfogel** [comment]
Note for those watching this issue: @bnazari is diving deep into the tables to fully delete the job.  Watch this space for updates.

**Comment by kfogel** [comment]
@OhMcGoo, do you know whether this got fully solved?  I don't want to go table-diving to verify for myself, but I will if I have to (unless @bnazari can confirm that it's done).

**Comment by OhMcGoo** [comment]
This has been resolved.
