### ISSUE TITLE
Data not coming across from Volunteer Connection

### ISSUE THREAD

**Issue by cliffhu** [redcross/arcdata#57]
This is only happening in the San Diego region.  Some new volunteers are not able to be seen in DCSOPs.  In fact their CID is being set to 0, even though they are not deployed.  Also, changes in GAPs, eg.,promotions are not coming across. Unfortunately, this has inhibited new member or newly promoted DAT members from being assigned correctly to shifts within DCSOPs.  An example of this is Denise Molnar. Her VC record looks correct, being assigned to the San Diego region, but her CID is 0 in DCSOPs.  According to Jim McGowan this problem is not being seen in other regions using DCSOPs.

Cliff

**Comment by cecilia-donnelly** [comment]
@OhMcGoo, can this be closed now?

**Comment by OhMcGoo** [comment]
The Volunteer Connection account used to sync data with DCSOps was deactivated by the San Diego Region's Volunteer Services staff due to inactivity. As such, volunteer data has not been syncing properly since late last year. On Sunday, January 17, the account was reactivated. On Monday, January 18, it appeared that all volunteer data was syncing properly and that users were no longer experiencing issues. This issue has been closed.
