### ISSUE TITLE
"Add other person" should take dispatcher to the responder "Assign" page

### ISSUE THREAD

**Issue by smille1834** [redcross/arcdata#70]
When dispatchers have to "Add other person," (assign a responder to an incident who isn't on the schedule) the contact information for the new responder isn't immediately available. When a dispatcher selects "Add other person" and types in the name of the requested responder, DCSOps should then take the dispatcher to that responders "Assign" page showing his/her contact information so the dispatcher can call that responder and confirm his/her status.

**Comment by cecilia-donnelly** [comment]
Hey @smille1834, are you referring to the responder tab on an incident?  Is this the path? `/incidents/arcil/incidents/16-003/dat/edit#form_responders`

I'm not sure if that page is used pre/during an incident or only after an incident.

**Comment by jasonwinget** [comment]
There should be an "other" reason for not assigning as well.  There is not available and no answer, but there may be another reason....i.e. just getting trainees off of the flex area of the console because you need more responders to show up in the time / distance calculation.  This also goes to the issue we need to be able to filter the flex console.

**Comment by jasonwinget** [comment]
@cecilia-donnelly this https://www.dcsops.org/incidents/southern_minnesota/incidents/16-2438/responders/new?person_id=30793 is when we are assigning someone during the incident.  They are assigned in a functional role on scene, many volunteers will have several positions but this functional role is based on the need of the incident.    My comment earlier was off topic, i miss read the initial comment.  The issue is in regards to a slightly different work flow to getting people on the incident.  Instead of using the "assign" the alternate is to use this other option, which is on the responder page upper left.  

Step 1 is to choose option:
![image](https://cloud.githubusercontent.com/assets/3647696/13200767/9ad5569e-d81c-11e5-9816-aaaf931e6476.png)


Step 1 look up person to assign, then step 2 is where this issue addressing the missing contact information and 3 is where I commented.
![image](https://cloud.githubusercontent.com/assets/3647696/13200771/c16d9cda-d81c-11e5-83f6-faa54e403de9.png)

**Comment by cecilia-donnelly** [comment]
@jasonwinget thanks so much!  The screenshots in particular are enormously helpful.  I think I understand now what you and @smille1834 are describing.  It seems like it would be best to add contact information on this page, where you have your "2" pointer, rather than taking the user to a different page.  Does that sound right?

**Comment by jasonwinget** [comment]
@cecilia-donnelly I would agree.  You could re-use code from the sub-window that opens when you click assign from responder console.  That takes into account the call order etc.
